import type { GetServerSideProps, NextPage } from 'next'

import Head from 'next/head'
import Image from 'next/image'

import Foo from '@/components/Foo'
import prefetchQueriesOnServer from '@/utils/prefetchQueriesOnServer'
import { prefetchHelloQuery } from '@/hooks/useHelloQuery'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Foo />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const dehydratedState = await prefetchQueriesOnServer([prefetchHelloQuery])
  return { props: { dehydratedState } }
}

export default Home
